variables:
  ServiceConnectionName: 'MoiseGermain-srvconn'
  Location: 'eastus'
  ResourceGroup: 'DronestatusRG'
  AppName: 'Dronestatus' # Ensure it's 11 characters or less
  DeployAzureResources: false
  DeployableSourceBranch: 'refs/heads/master'
  SlotName: 'staging (dronespy22arfo5ur6y-dronestatus/staging)'

name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  branches:
    include:
    - master
    - feature/* # ci-only

resources:
- repo: self

jobs:

# CI
- job: dronestatusjobci
  displayName: "Drone Status CI"
  steps:
  - template: ./src/DroneStatus/azure-pipelines-ci.yml

# CD
- job: dronestatuscd
  dependsOn: dronestatusjobci
  condition: and(succeeded('dronestatusjobci'), eq(variables['build.sourceBranch'], variables['DeployableSourceBranch']))
  displayName: "Drone Status CD"
  steps:
  - template: ./src/DroneStatus/azure-pipelines-cd.yml
